In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import seaborn as sns

In [4]:
df1=sns.load_dataset('tips')
df2=sns.load_dataset("Titanic")

# Head aur Tail :- Methods
time complexity is more than attributes

In [5]:
df1.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [6]:
df1.head(12)

    total_bill   tip     sex smoker  day    time  size
0        16.99  1.01  Female     No  Sun  Dinner     2
1        10.34  1.66    Male     No  Sun  Dinner     3
2        21.01  3.50    Male     No  Sun  Dinner     3
3        23.68  3.31    Male     No  Sun  Dinner     2
4        24.59  3.61  Female     No  Sun  Dinner     4
5        25.29  4.71    Male     No  Sun  Dinner     4
6         8.77  2.00    Male     No  Sun  Dinner     2
7        26.88  3.12    Male     No  Sun  Dinner     4
8        15.04  1.96    Male     No  Sun  Dinner     2
9        14.78  3.23    Male     No  Sun  Dinner     2
10       10.27  1.71    Male     No  Sun  Dinner     2
11       35.26  5.00  Female     No  Sun  Dinner     4

In [7]:
df1.tail(2)

     total_bill   tip     sex smoker   day    time  size
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

# SHAPES :- Attribute

In [8]:
print(df1.shape)

(244, 7)

In [9]:
print(df2.shape)

(891, 15)

#datatypes

In [10]:
print(df1.dtypes)
print()

total_bill     float64
tip            float64
sex           category
smoker        category
day           category
time          category
size             int64
dtype: object

In [11]:
print(df2.dtypes)
print()

survived         int64
pclass           int64
sex             object
age            float64
sibsp            int64
parch            int64
fare           float64
embarked        object
class           object
who             object
adult_male        bool
deck            object
embark_town     object
alive           object
alone             bool
dtype: object

# Index

In [12]:
print(df1.index)
print(df2.index)

RangeIndex(start=0, stop=244, step=1)
RangeIndex(start=0, stop=891, step=1)

In [13]:
print(df1.columns)
print(df2.columns)

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')
Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [14]:
print(df1.values)

[[16.99 1.01 'Female' ... 'Sun' 'Dinner' 2]
 [10.34 1.66 'Male' ... 'Sun' 'Dinner' 3]
 [21.01 3.5 'Male' ... 'Sun' 'Dinner' 3]
 ...
 [22.67 2.0 'Male' ... 'Sat' 'Dinner' 2]
 [17.82 1.75 'Male' ... 'Sat' 'Dinner' 2]
 [18.78 3.0 'Female' ... 'Thur' 'Dinner' 2]]

## SAMPLE

sample gives onlyone row as outputs

In [15]:
df1.sample(10)

     total_bill   tip     sex smoker   day    time  size
134       18.26  3.25  Female     No  Thur   Lunch     2
126        8.52  1.48    Male     No  Thur   Lunch     2
139       13.16  2.75  Female     No  Thur   Lunch     2
38        18.69  2.31    Male     No   Sat  Dinner     3
33        20.69  2.45  Female     No   Sat  Dinner     4
82        10.07  1.83  Female     No  Thur   Lunch     1
63        18.29  3.76    Male    Yes   Sat  Dinner     4
44        30.40  5.60    Male     No   Sun  Dinner     4
114       25.71  4.00  Female     No   Sun  Dinner     3
85        34.83  5.17  Female     No  Thur   Lunch     4

## Info :- information about the dataframe

In [16]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [17]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    object
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    object
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), float64(2), int64(4), object(7)
memory usage: 92.4+ KB

## Describe:- mathematical value find out

In [18]:
df1.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [19]:
df2.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [20]:
df1.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [21]:
print(df1.duplicated().sum())

1

In [22]:
print(df2.duplicated().sum())

107

In [23]:
x=df1.rename(columns={'size':"no","tip":'Tips'},)
print(x)

     total_bill  Tips     sex smoker   day    time  no
0         16.99  1.01  Female     No   Sun  Dinner   2
1         10.34  1.66    Male     No   Sun  Dinner   3
2         21.01  3.50    Male     No   Sun  Dinner   3
3         23.68  3.31    Male     No   Sun  Dinner   2
4         24.59  3.61  Female     No   Sun  Dinner   4
..          ...   ...     ...    ...   ...     ...  ..
239       29.03  5.92    Male     No   Sat  Dinner   3
240       27.18  2.00  Female    Yes   Sat  Dinner   2
241       22.67  2.00    Male    Yes   Sat  Dinner   2
242       17.82  1.75    Male     No   Sat  Dinner   2
243       18.78  3.00  Female     No  Thur  Dinner   2

[244 rows x 7 columns]

In [24]:
x=df1.rename(columns={'size':"no","tip":'Tips'},inplace=True)

In [25]:
df2.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [26]:
x=df2.rename(columns={'embark_town':"embark",'deck':"cabin"})
print(x)

     survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third
1           1       1  female  38.0      1      0  71.2833        C   First
2           1       3  female  26.0      0      0   7.9250        S   Third
3           1       1  female  35.0      1      0  53.1000        S   First
4           0       3    male  35.0      0      0   8.0500        S   Third
..        ...     ...     ...   ...    ...    ...      ...      ...     ...
886         0       2    male  27.0      0      0  13.0000        S  Second
887         1       1  female  19.0      0      0  30.0000        S   First
888         0       3  female   NaN      1      2  23.4500        S   Third
889         1       1    male  26.0      0      0  30.0000        C   First
890         0       3    male  32.0      0      0   7.7500        Q   Third

       who  adult_male cabin       embark alive  alone
0      man        True   NaN  Southampton    no  False
1    woman       False     C    Cherbourg   yes  False
2    woman       False   NaN  Southampton   yes   True
3    woman       False     C  Southampton   yes  False
4      man        True   NaN  Southampton    no   True
..     ...         ...   ...          ...   ...    ...
886    man        True   NaN  Southampton    no   True
887  woman       False     B  Southampton   yes   True
888  woman       False   NaN  Southampton    no  False
889    man        True     C    Cherbourg   yes   True
890    man        True   NaN   Queenstown    no   True

[891 rows x 15 columns]

In [27]:
df1['Tips']

0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ...
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: Tips, Length: 244, dtype: float64

In [28]:
df2['sex']

0        male
1      female
2      female
3      female
4        male
        ...
886      male
887    female
888    female
889      male
890      male
Name: sex, Length: 891, dtype: object

In [29]:
df1[['Tips','sex','day']]

     Tips     sex   day
0    1.01  Female   Sun
1    1.66    Male   Sun
2    3.50    Male   Sun
3    3.31    Male   Sun
4    3.61  Female   Sun
..    ...     ...   ...
239  5.92    Male   Sat
240  2.00  Female   Sat
241  2.00    Male   Sat
242  1.75    Male   Sat
243  3.00  Female  Thur

[244 rows x 3 columns]

##SLICING

In [30]:
df1.iloc[18:5:-6]

    total_bill  Tips     sex smoker  day    time  no
18       16.97  3.50  Female     No  Sun  Dinner   3
12       15.42  1.57    Male     No  Sun  Dinner   2
6         8.77  2.00    Male     No  Sun  Dinner   2

In [31]:
df1.iloc[[5,6,12,14]]

    total_bill  Tips     sex smoker  day    time  no
5        25.29  4.71    Male     No  Sun  Dinner   4
6         8.77  2.00    Male     No  Sun  Dinner   2
12       15.42  1.57    Male     No  Sun  Dinner   2
14       14.83  3.02  Female     No  Sun  Dinner   2

Slicing using both rows and columns

iloc :- it works on indexing
loc :- it works on the data value index

In [32]:
df1.iloc[0:3,0:7]

   total_bill  Tips     sex smoker  day    time  no
0       16.99  1.01  Female     No  Sun  Dinner   2
1       10.34  1.66    Male     No  Sun  Dinner   3
2       21.01  3.50    Male     No  Sun  Dinner   3

In [33]:
df1.loc[0:8:2,'time':'no']

     time  no
0  Dinner   2
2  Dinner   3
4  Dinner   4
6  Dinner   2
8  Dinner   2

In [34]:
df1.head(3)

   total_bill  Tips     sex smoker  day    time  no
0       16.99  1.01  Female     No  Sun  Dinner   2
1       10.34  1.66    Male     No  Sun  Dinner   3
2       21.01  3.50    Male     No  Sun  Dinner   3

## astype()

In [35]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   Tips        244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   no          244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [36]:
df1['Tips'] = df1['Tips'].astype('float16')

In [37]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   Tips        244 non-null    float16
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   no          244 non-null    int64
dtypes: category(4), float16(1), float64(1), int64(1)
memory usage: 5.9 KB

In [38]:
df2['survived'] = df2['survived'].astype('int32')

In [39]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int32
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    object
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    object
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), float64(2), int32(1), int64(3), object(7)
memory usage: 88.9+ KB

## value_counts

In [40]:
df1['Tips'].value_counts()

Tips
2.000000    33
3.000000    23
4.000000    12
2.500000    10
5.000000    10
            ..
1.469727     1
1.169922     1
4.671875     1
5.921875     1
1.750000     1
Name: count, Length: 123, dtype: int64

## PROJECT NO. :- 02 (STUDENT PERFORMANCE)